
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11.0

[colors]
[colors.primary]
  background = '0x121212'
  foreground = '0xD4D4D4'

[general]
live_config_reload = true
